const SEED_PLOTS: Record<string, string> = {
  "Harry Potter and the Sorcerer's Stone|J.K. Rowling": `Harry Potter is a young orphan who lives with the Dursleys, his cruel aunt and uncle. Harry discovers on his eleventh birthday that he is a wizard. Hagrid tells Harry about his magical heritage and his parents who were killed by the dark wizard Voldemort. Harry enters Hogwarts School of Witchcraft and Wizardry. Harry meets Ron Weasley on the train to Hogwarts. Hermione Granger becomes one of Harry's closest friends at school. The three friends learn about the Sorcerer's Stone, which grants immortality. They suspect their teacher Snape wants to steal the stone. Harry, Ron, and Hermione pass through dangerous magical challenges guarding the stone. Hermione solves a logic puzzle that protects the stone. Ron sacrifices himself during a life-sized wizard chess game. Harry faces Professor Quirrell, who is possessed by Voldemort. Harry stops Voldemort from returning to power and wins the house cup with his friends.`,

  "The Hobbit|J.R.R. Tolkien": `Bilbo Baggins is a hobbit who enjoys a quiet life in the Shire. Gandalf the wizard arrives with thirteen dwarves led by Thorin Oakenshield. The dwarves recruit Bilbo as a burglar for their quest to reclaim Erebor. The company travels through dangerous lands toward the Lonely Mountain. Bilbo gets lost in goblin tunnels and finds a magic ring. Bilbo meets Gollum and escapes by using the ring to become invisible. Bilbo later uses his wits to help the group escape giant spiders and elven prisons. The dragon Smaug guards the treasure inside the mountain. Bard the archer later slays Smaug and protects Lake-town. Thorin becomes obsessed with the treasure and refuses to share. A battle threatens between dwarves, elves, and men before peace is restored. Bilbo returns home with a share of treasure and a secret magic ring. Gandalf helps Bilbo begin the adventure that changes his quiet life forever.`,

  "Charlotte's Web|E.B. White": `Wilbur is a young pig who is born on the Arable farm. Fern saves Wilbur when he is about to be killed because he is the runt. Wilbur is later sent to live at the Zuckerman barn. Wilbur feels lonely until he meets Charlotte, a wise spider. Wilbur learns that Mr. Zuckerman plans to slaughter him for food. Charlotte promises to save Wilbur's life. Charlotte weaves words like "Some Pig" into her web above Wilbur's pen. People come from far away to see the miraculous pig. Charlotte later lays eggs, but she grows weak and dies. Wilbur protects Charlotte's egg sac through the winter. In spring, Charlotte's children hatch and most leave the barn. Three of Charlotte's daughters stay with Wilbur as his friends. Templeton the rat helps Wilbur by finding words for Charlotte's web.`,

  "Percy Jackson and the Lightning Thief|Rick Riordan": `Percy Jackson is a twelve-year-old boy who struggles in school and often gets into trouble. Percy learns that he is a demigod and the son of Poseidon. Zeus accuses Percy of stealing his master lightning bolt. Percy must travel to the Underworld to find the bolt and prevent a war among the gods. Percy leaves Camp Half-Blood with his friends Annabeth and Grover. Annabeth helps Percy fight monsters with her clever battle plans. Grover protects Percy as they travel across America. The trio faces monsters and gods on their journey across America. They travel to Los Angeles and enter the realm of Hades. Percy discovers the true thief and returns the lightning bolt to Olympus. Percy learns that friendship and loyalty helped him survive the quest. Percy returns to camp and learns more about his powers and family. Annabeth proves her courage during the dangerous quest with Percy and Grover.`,

  "Wonder|R.J. Palacio": `August Pullman is a boy born with facial differences that make him look unusual. Auggie has been homeschooled, but his parents decide he should start fifth grade at Beecher Prep. Auggie is nervous about meeting other students and being accepted. Auggie befriends Jack Will and Summer at school. Julian bullies and excludes Auggie at Beecher Prep. Via struggles with her own friendships while supporting her brother. The family dog Daisy dies, which deeply hurts the Pullman family. Auggie faces betrayal when he overhears Jack say cruel things about him. Jack later apologizes and their friendship grows stronger. Summer sits with Auggie at lunch when other students avoid him. Auggie earns respect during a camping trip when he shows courage. At graduation, Auggie receives a special award for kindness and strength. Via stands by Auggie when school becomes difficult for their family.`,

  "The Remarkable Journey of Coyote Sunrise|Dan Gemeinhart": `Coyote Sunrise is a twelve-year-old girl traveling the country with her father Rodeo in an old school bus. Years earlier, Coyote's mother and sisters died in a car crash in Oregon. Rodeo changed their names and keeps driving to avoid painful memories from home. Coyote learns that the park in Oregon where she buried a memory box will soon be destroyed. Coyote secretly plans a journey back to Oregon without telling Rodeo the real reason. Coyote and Rodeo pick up a musician named Lester who needs to reach Austin. Coyote and Rodeo also meet Val, a teenage girl running away from problems at home. Salvador and his mother join the trip while escaping a dangerous situation. Coyote helps each new friend solve a problem during the journey. Rodeo becomes angry when he discovers Coyote's secret plan to return to Oregon. Coyote and her friends must work together when the bus breaks down on the road. Coyote finally reaches Oregon and digs up the memory box she buried with her mother and sisters. Coyote and Rodeo begin to heal and talk honestly about their grief. Lester plays music that keeps everyone hopeful during the long trip.`,
};

export function getSeedPlot(bookTitle: string, author: string): string | null {
  const key = `${bookTitle}|${author}`;
  return SEED_PLOTS[key] ?? null;
}

export function getSeedPlotKeys(): string[] {
  return Object.keys(SEED_PLOTS);
}
